### ISSUE TITLE
Springs don't connect to Steve's Carts.

### ISSUE THREAD

**Issue by Ooles** [jglrxavpok/Entity-Spring#6]
Mod doesn't work with Steve's Carts Reborn 2.4.18.92 on 1.12.2. Rightclicking and shiftclicking carts with springs in hand just opens cart's gui.

**Comment by jglrxavpok** [comment]
Which version of EntitySpring do you have?

**Comment by Ooles** [comment]
1.1.0

**Comment by jglrxavpok** [comment]
Fixed in commit https://github.com/jglrxavpok/Entity-Spring/commit/fe33cb6ff5fd181b78e024c74313c4ef6954148c
The new release will be available there: https://minecraft.curseforge.com/projects/entity-spring/files/2552433 (once Curse has approved the file)

~~Also your issue made me notice that I was doing something wrong in Moar Boats so thank you! :) ~~

EDIT: Actually Moar Boats did not have the same problem but now I'm sure it won't have it
